Repository catchroom/BE_Chat, pull requests merged in 2024-01, with the labels that each got.

#12 Feat : 네고하기
  src/main/java/com/catchroom/ChatApplication.java
  src/main/java/com/catchroom/chat/message/feign/MainFeignClient.java
  src/main/java/com/catchroom/chat/message/type/MessageType.java
Labels: 🌎 Deploy, 🌟 Feat

#13 Feat : 네고하기 - 네고 가격 추가
  src/main/java/com/catchroom/chat/message/dto/ChatMessageDto.java
  src/main/java/com/catchroom/chat/message/entity/ChatMessage.java
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
Labels: 🌎 Deploy, 🌟 Feat

#14 Style : feign global 로 이동
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/feign/controller/MainFeignController.java
  src/main/java/com/catchroom/chat/feign/service/MainFeignService.java
Labels: 🔨 Refactor, ✏️ Style

#15 Feat : 채팅방 등장하기, 나가기 삭제
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌟 Feat

#16 채팅방 나가기, 등장하기 기능 배포
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomCreateRequest.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomCreateResponse.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/catchroom/chat/chatroom/repository/ChatRoomRepositoryJPA.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/feign/controller/MainFeignController.java
  src/main/java/com/catchroom/chat/feign/service/MainFeignService.java
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/main/java/com/catchroom/chat/message/type/UserIdentity.java
Labels: 🌎 Deploy

#17 fix : main client 핫픽스
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
Labels: 🌎 Deploy

#18 Feat : 마지막 메시지 저장
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌟 Feat

#19 Feature/채팅방조회feign적용
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/global/config/FeignConfig.java
Labels: 🌟 Feat

#20 Develop
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/catchroom/chat/chatroom/repository/ChatRoomRepositoryJPA.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/feign/controller/MainFeignController.java
  src/main/java/com/catchroom/chat/feign/dto/AccommodationResponse.java
  src/main/java/com/catchroom/chat/feign/service/MainFeignService.java
  src/main/java/com/catchroom/chat/global/config/FeignConfig.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#22 Refactor : CORS에러 해결
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/feign/controller/MainFeignController.java
  src/main/java/com/catchroom/chat/global/config/WebConfig.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/controller/ChatFindController.java
  src/main/java/com/catchroom/chat/message/dto/ChatMessageDto.java
  src/main/java/com/catchroom/chat/message/entity/ChatMessage.java
Labels: 🌎 Deploy

#24 hotfix : serializable 수정
  src/main/java/com/catchroom/chat/message/dto/ChatMessageDto.java
Labels: 🌎 Deploy

#25 Feat room list
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/dto/MessageSubDto.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌟 Feat

#27 fix : 룸 정보 pub sub 추가
  src/main/java/com/catchroom/chat/global/pubsub/RedisPublisher.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: ⛑️ fix

#28 Develop
  src/main/java/com/catchroom/chat/global/pubsub/RedisPublisher.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#29 hotfix : error msg
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
Labels: 🌎 Deploy

#30 hotfix : error
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
Labels: ⛑️ fix

#32 Develop
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
Labels: 🌎 Deploy

#33 Develop
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#34 Feat : 메세지 리스트 최신순 정렬 로직 추가
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#35 Fix : 메세지 리스트 최신순 정렬 로직 fix
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#36 Fix : 메세지 리스트 최신순 정렬 로직 fix
  src/main/java/com/catchroom/chat/test/MessageSortController.java
Labels: 🌎 Deploy

#37 Fix : 메세지 리스트 최신순 정렬 로직 fix
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/test/MessageSortController.java
Labels: 🌎 Deploy

#38 Fix : 최초 채팅방 리스트 조회 시 최신화 리스트 조회 로직 반영
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/test/MessageSortController.java
Labels: 🌎 Deploy

#39 Fix : 최초 채팅방 리스트 조회 시 최신화 리스트 조회 로직 반영
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/type/DealState.java
Labels: 🌎 Deploy

#40 sender 필드 삭제
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/global/common/SuccessMessage.java
  src/main/java/com/catchroom/chat/message/dto/ChatMessageDto.java
  src/main/java/com/catchroom/chat/message/entity/ChatMessage.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
  src/main/java/com/catchroom/chat/message/type/MessageType.java
  src/main/java/com/catchroom/chat/test/MessageSortController.java
Labels: 🌟 Feat

#41 fix : cors error
  src/main/java/com/catchroom/chat/message/controller/ChatFindController.java
Labels: ⛑️ fix

#42 feat : 채팅방 삭제 로직 추가
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/feign/client/MainFeignClientTest.java
Labels: 🌟 Feat

#43 채팅방 삭제 배포
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/feign/client/MainFeignClientTest.java
Labels: 🌎 Deploy

#44 feat : 채팅방 수정
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
Labels: ⛑️ fix

#45 style : 채팅방 pub 주석 제거
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#46 style : 채팅방 pub 로그 추가
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy, ✏️ Style

#47 style : 채팅방 pub 로그 추가
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/type/ChatRoomState.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#48 Develop 배포
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#49 fix : redis conf 수정
  src/main/java/com/catchroom/chat/global/config/RedisConfig.java
  src/main/java/com/catchroom/chat/global/config/properties/RedisProperties.java
Labels: 🌎 Deploy

#50 Feat : CORS 에러 해결 코드 추가
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/type/DealState.java
  src/main/java/com/catchroom/chat/feign/controller/MainFeignController.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/controller/ChatFindController.java
  src/main/java/com/catchroom/chat/test/MessageSortController.java
Labels: 🌎 Deploy

#51 Feat : 채팅내역불러오기 Paging 처리
  src/main/java/com/catchroom/chat/message/controller/ChatFindController.java
  src/main/java/com/catchroom/chat/message/dto/ChatMessageDto.java
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
Labels: 🌎 Deploy, 🌟 Feat

#53 Develop restTemplate 테스트
  build.gradle
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
Labels: 🌎 Deploy, 🔨 Refactor

#54 refactor : restTemplate TTL 설정
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
Labels: 🔨 Refactor

#55 redisTemplate TTL 설정
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
Labels: 🌎 Deploy

#56 fix : code 정리
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: ⛑️ fix

#57 Develop 배포
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#58 Feature/refactor chat 만료시간 설정 취소
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
Labels: ⛑️ fix

#59 Develop 배포
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRepository.java
Labels: 🌎 Deploy

#60 Feat : 채팅내역불러오기 Paging 순서 변경
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
Labels: 🌎 Deploy

#61 Feat : 채팅내역불러오기 Paging 순서 변경
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
Labels: ⛑️ fix, 🌎 Deploy

#62 Feature/refactor 채팅방 리스트 레디스 저장
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🔨 Refactor

#63 Develop 배포
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/global/handler/StompHandler.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/controller/ChatController.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#64 refactor : redis 채팅방 급하게 수정
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
Labels: ⛑️ fix

#65 Develop
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
Labels: 🌎 Deploy

#66 feat : 채팅방 내부 정보 불러오기 api 완성
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌟 Feat

#67 Develop 배포
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/client/MainFeignClient.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
Labels: 🌎 Deploy

#68 style : 시간 확인용 에러 로그 추가
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#69 refactor : 채팅방 레디스로 불러오도록 리팩토링
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🔨 Refactor

#70 refactor : 채팅방 리팩토링 배포
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy, 🔨 Refactor

#71 수정수정
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🔨 Refactor

#72 Develop 원본 재배포
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#73 refactor : 레디스 사용하여 채팅방 로직 수정
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#74 Develop 배포
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: 🌎 Deploy

#75 style : log 추가
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#76 fix : 마지막 메세지들 저장 후 정렬 추가
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#77 Develop 에러 핸들러 추가
  src/main/java/com/catchroom/chat/global/exception/GlobalExceptionHandler.java
Labels: 🌟 Feat

#78 refactor : 채팅방 리팩토링
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/dto/AccommodationResponse.java
  src/main/java/com/catchroom/chat/feign/dto/RoomResponse.java
  src/main/java/com/catchroom/chat/message/dto/ChatRoom.java
  src/main/java/com/catchroom/chat/message/repository/ChatMessageRepository.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: 🔨 Refactor

#79 Develop
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/feign/dto/AccommodationResponse.java
  src/main/java/com/catchroom/chat/feign/dto/RoomResponse.java
  src/main/java/com/catchroom/chat/global/exception/GlobalExceptionHandler.java
  src/main/java/com/catchroom/chat/message/dto/ChatRoom.java
  src/main/java/com/catchroom/chat/message/repository/ChatMessageRepository.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatMongoService.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: 🌎 Deploy, 🔨 Refactor

#80 fix : 상대편 채팅방도 레디스에 추가
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: ⛑️ fix, 🔨 Refactor

#81 Develop 배포
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#82 fix : 상대편 채팅방도 레디스에 추가
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: ⛑️ fix

#83 Develop 배포
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: ⛑️ fix, 🌎 Deploy

#84 fix : pub-sub시 채팅방 리스트도 상대방 id에 보내도록 수정
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/dto/MessageSubDto.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: ⛑️ fix, 🔨 Refactor

#85 Develop
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/global/pubsub/RedisSubscriber.java
  src/main/java/com/catchroom/chat/message/dto/MessageSubDto.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/service/ChatServiceTest.java
Labels: 🌎 Deploy

#86 fix : 채팅방 정렬시 마지막 메시지 넣도록 수정
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: ⛑️ fix

#87 Develop
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#89 Develop
  src/main/java/com/catchroom/chat/chatroom/dto/ChatRoomListGetResponse.java
  src/main/java/com/catchroom/chat/global/config/RedisConfig.java
  src/main/java/com/catchroom/chat/message/repository/ChatRoomRedisRepository.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
  src/test/java/com/catchroom/chat/message/repository/ChatRoomRedisRepositoryTest.java
Labels: 🌎 Deploy

#90 fix : 최근 메시지 없는 것들은 채팅방 목록에서 안보이도록 수정
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: ⛑️ fix

#91 Develop
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy

#92 fix : 최근 메시지 없는 것들은 로직에서 추가 안하도록 재수정
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: ⛑️ fix

#93 Develop
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/catchroom/chat/message/service/ChatService.java
Labels: 🌎 Deploy

#97 Refactor : Import문 정렬
  src/main/java/com/catchroom/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/catchroom/chat/chatroom/service/ChatRoomService.java
Labels: 🌎 Deploy
